---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WinterSky.
--- DateTime: 2018/8/22 8:40
---
package.path = package.path .. ";D:/WinterSky/Documents/AndroidStudio/WindyReader/app/src/main/assets/?.lua"
require("lua_api.util")
local lib = require("www_8wenku_com")
local http = require("socket.http")

local bookUrl = "http://www.8wenku.com/book/1871"
local catalogUrl = "http://www.8wenku.com/book/1871"
local chapterUrl = "http://www.8wenku.com/chapter/view?id=1871&chapter_no=1"

local bookDoc = http.request(bookUrl)
local catalogDoc = http.request(catalogUrl)
local chapterDoc = http.request(chapterUrl)

local book = lib.getBook(bookUrl, bookDoc)
local catalog = lib.getCatalog(catalogUrl, catalogDoc)
local chapter = lib.getChapter(chapterUrl, chapterDoc)

print(book)
print(catalog)
print(chapter)