---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by WinterSky.
--- DateTime: 2018/8/21 19:33
---
package.path = package.path .. ";D:/WinterSky/Documents/AndroidStudio/WindyReader/app/src/main/assets/?.lua"
require("lua_api.util")
local lib = require("zxzw_com")
local http = require("socket.http")

local bookUrl = "http://zxzw.com/164718/"
local catalogUrl = "http://zxzw.com/164718/"
local chapterUrl = "http://zxzw.com/164718/14181340/"

local bookDoc = http.request(bookUrl)
local catalogDoc = http.request(catalogUrl)
local chapterDoc = http.request(chapterUrl)

local book = lib.getBook(bookUrl, bookDoc)
local catalog = lib.getCatalog(catalogUrl, catalogDoc)
local chapter = lib.getChapter(chapterUrl, chapterDoc)

print(book)
print(catalog)
print(chapter)