---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tiandong.
--- DateTime: 18-3-15 下午1:18
---
local M = {}
connection = M

M.con = nil

function connection:new(con)
    local o = {}
    self.__index = self
    setmetatable(o, self)
    o.con = con
    return o
end

function M:get()
    local doc = __doc or self.con:get()
    g_doc = nil
    return document:new(doc)
end

function M:post()
    local doc = __doc or self.con:post()
    g_doc = nil
    return document:new(doc)
end

function M:data(sKey, sValue)
    self.con:data(sKey, sValue)
    return self
end

return connection