---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tiandong.
--- DateTime: 18-3-14 下午5:45
---
local M = {}
element = M

M.e = nil

function M:new(e)
    local o = {}
    self.__index = self
    setmetatable(o, self)
    o.e = e
    return o
end

function M:select(sQuery)
    local es = self.e:select(sQuery)
    return elements:new(es)
end

function M:text()
    return self.e:text()
end

function M:ownText()
    return self.e:ownText()
end

function M:toString()
    return self.e:toString()
end

function M:attr(sKey)
    return self.e:attr(sKey)
end

function M:parent()
    local e = self.e:parent()
    return element:new(e)
end

function M:tagName()
    return self.e:tagName()
end

function M:firstElementSibling()
    local e = self.e:firstElementSibling()
    return element:new(e)
end

function M:previousElementSibling()
    local e = self.e:previousElementSibling()
    return element:new(e)
end

function M:nextElementSibling()
    local e = self.e:nextElementSibling()
    return element:new(e)
end

function M:lastElementSibling()
    local e = self.e:lastElementSibling()
    return element:new(e)
end

return element