---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tiandong.
--- DateTime: 18-3-14 下午5:45
---
local M = {}
elements = M

M.es = nil

function M:new(es)
    local o = {}
    self.__index = self
    setmetatable(o, self)
    o.es = es
    return o
end

function M:select(sQuery)
    local es = self.es:select(sQuery)
    return elements:new(es)
end

function M:toString()
    return self.es:toString()
end

function M:text()
    return self.es:text()
end

function M:get(i)
    local e = self.es:get(i)
    return element:new(e)
end

function M:after(sAdd)
    self.es:after(sAdd)
end

function M:size()
    return self.es:size()
end

function M:isEmpty()
    return self.es:isEmpty()
end

return elements