---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tiandong.
--- DateTime: 18-3-14 下午5:43
---
local M = {}
jsoup = M

local Jsoup = luajava.bindClass("org.jsoup.Jsoup")

function M:connect(sUrl)
    local con = Jsoup:connect(sUrl)
    return connection:new(con)
end

return jsoup