---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by tiandong.
--- DateTime: 18-3-14 下午8:46
---
require("jsoup")
require("connection")
require("document")
require("elements")
require("element")

Android_Log = luajava.bindClass("android.util.Log")
LT = "wintersky"
function log(sMsg)
    Android_Log:i(LT, sMsg)
end

function Chapter()
    return luajava.newInstance("com.wintersky.windyreader.data.Chapter")
end

function Book()
    return luajava.newInstance("com.wintersky.windyreader.data.Book")
end


